version: "2.4"
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: IceHrmR00t
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: icehrm
    volumes:
      - ./docker/development/init.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./docker/development/db_data:/var/lib/mysql

  icehrm:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/var/www/html

  icehrm-worker-dev:
    build:
      context: ./
      dockerfile: Dockerfile-worker
      args:
        - EXE_ENV=development
volumes:
  db_data:
