version: "3.5"
services:
  mysql-prod:
    image: mysql:5.7
    ports:
      - 3000:3000
    environment:
      MYSQL_ROOT_PASSWORD: IceHrmR00t
      MYSQL_USER: prod
      MYSQL_PASSWORD: prod
      MYSQL_DATABASE: icehrm
    volumes:
      - ./docker/prod/init.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./docker/prod/db_data:/var/lib/mysql

  icehrm-prod:
    build:
      context: ./
      dockerfile: Dockerfile-prod
    ports:
      - 8070:8070
    volumes:
      - ./docker/prod/app_data:/var/www/html/app/data

  icehrm-worker:
    build:
      context: ./
      dockerfile: Dockerfile-worker
      args:
        - EXE_ENV=prod
volumes:
  db_data:
  app_data:
